name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.33.6
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: Install dependencies
      run: pnpm install
    
    - name: generate prisme
      run: pnpm run prisma:generate

    - name: Build
      run: pnpm run build
    
    - name: Type Check
      run: pnpm run type-check
    
    - name: Lint
      run: pnpm run lint
    
    - name: Backend Unit Tests
      run: pnpm --filter backend test
    
    - name: Backend Integration Tests
      run: pnpm --filter backend test:integration
    
    - name: Backend All Tests
      run: pnpm --filter backend test:all
    
    - name: Frontend Tests
      run: pnpm --filter frontend test
